# Default site settings

sitename = "Lessmarcos.com"
title = "Lessmarcos"
author = "Marcos"
layout = "base_layout"
description = "Lessmarcos.com"

content_dir = [
    "posts",
]
templates_dir = "templates"
output_dir = "dist"
static_dir = "static"

partials = [
    "head",
    "footer",
    "scripts",
    "highlighter",
    "reload",
    "nav",
]
